apiVersion: v1
kind: ReplicationController
metadata:
  name: swops-flask
  labels:
    name: swops-flask
    app: coding-challenge
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: swops-flask
    spec:
      containers:
        - name: swops-flask
          image: carlherbst/swops-flask:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP